[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
via_ir = true
solc_version = '0.8.17'
optimizer_runs = 1_000_000
fs_permissions = [{ access = "read", path = "./script/deployParameters/"}]

[fmt]
line_length = 120
quote_style = 'single'

[profile.lite.optimizer_details.yulDetails]
optimizerSteps = ''

[rpc_endpoints]
tokamakgoerli = "https://goerli.optimism.tokamak.network"

[etherscan]
tokamakgoerli = {key = "WM7SZ8W48JWGVZ7CA2QHJMM76SW45UPB38", url = "https://goerli.explorer.tokamak.network/api"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
